apiVersion: {{ .Values.ingress.apiVersion }}
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    {{- with .Values.ingress.additionalAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    app: {{ .Chart.Name }}
    appVersion: {{ .Chart.AppVersion }}
    helmVersion: {{ .Chart.Version }}
  name: {{ .Chart.Name }}-swagger
spec:
  rules:
  - host: {{ .Values.ingress.swaggerhost }}.{{ .Values.ingress.domain }}
    http:
      paths:
      - backend:
          service: 
            name: securebanking-ui-swagger
            port:
              number: 80
        path: /
        pathType: Prefix       
  tls:
  - hosts:
    - "{{ .Values.ingress.swaggerhost }}.{{ .Values.ingress.domain }}"
    secretName: {{ .Values.ingress.tls.secretName }}
