deployment:
  urls:
    ig:
      server: tpp.sbat.demo
    authorization:
      server: am.sbat.demo
    rcs:
      server: rcs.sbat.demo
    rs:
      server: rs.sbat.demo

rcsUI:
  subdomain: consent
  deployment:
    port: 80
    replicas: 1

    templateName: forgerock

    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 25%

    imagePullPolicy: Never

    imageOverride:
      enabled: true
      repo: securebanking-rcs-ui
      tag: latest

    resources: {}

swaggerUI:
  subdomain: swagger
  deployment:
    port: 80
    replicas: 1

    templateName: forgerock
    urls:
      swagger:
        json: swagger.sbat.demo

    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 25%

    imagePullPolicy: Never

    imageOverride:
      enabled: true
      repo: securebanking-swagger-ui
      tag: latest

    resources: {}

ingress:
  apiVersion: networking.k8s.io/v1
  class: nginx
  additionalAnnotations:
    nginx.ingress.kubernetes.io/client-body-buffer-size: 1m
    nginx.ingress.kubernetes.io/proxy-body-size: 150m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 100k
  domain: sbat.demo
  subdomain: consent
  swaggerhost: swagger
  consenthost: consent
  tls:
    subdomain: consent
    secretName: server.tls

apiVersion:
  service: v1
  deployment: apps/v1
